# Generated by Django 3.0.4 on 2020-03-30 21:57

from django.db import migrations


cities_list = [
    "New York",
    "New City",
    "Newgate",
    "South Creek",
    "South London",
    "Southern Rails",
    "Lake Cassidy",
    "Lake Something",
    "Lakes of Else",
]

def forwards_func(apps, schema_editor):
    City = apps.get_model("demo", "City")

    cities = [
        City(name=name) for name in cities_list
    ]
    City.objects.bulk_create(cities)

def reverse_func(apps, schema_editor):
    City = apps.get_model("demo", "City")
    City.objects.filter(name__in=cities_list).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        # Elidable determines whether or not the operation will be removed when squashing migrations.
        migrations.RunPython(forwards_func, reverse_func, elidable=False)
    ]
